-- The implicit syntax for an inner join 
	SELECT select_list 
	FROM table_1, table_2 [, table_3]... 
	WHERE table_1.column_name operator table_2.column_name 
		[AND table_2.column_name operator table_3.column_name]... 